### ISSUE TITLE
Room List

### ISSUE THREAD

**Issue by Hr24612** [microsoftgraph/msgraph-training-nodeexpressapp#13]
Hello,

I want to get access to the calendar rooms list through this API. Any advice on how to do that?

**Comment by jasonjoh** [comment]
https://docs.microsoft.com/en-us/graph/api/user-findrooms?view=graph-rest-beta&tabs=javascript and https://docs.microsoft.com/en-us/graph/api/user-findroomlists?view=graph-rest-beta&tabs=javascript have information on how to access rooms and room lists in Microsoft Graph, as well as sample JavaScript code.

**Comment by Hr24612** [comment]
Yeah, that might help. Thank you!

**Comment by Hr24612** [comment]
Do you know how the post request would look like if I want to know the
events of each room?
