### ISSUE TITLE
Update Demo to use msgraph-sdk-javascript 2.0

### ISSUE THREAD

**Issue by mlichtblau** [microsoftgraph/msgraph-training-nodeexpressapp#19]
This demo is based on msgraph-sdk-javascript 1.7.0.
However version 2.0.0 has been released and introduced some breaking changes detailed in this [migration guide](https://github.com/microsoftgraph/msgraph-sdk-javascript/wiki/Migration-from-1.x.x-to-2.x.x).
When trying to recreate the demo project with the new version errors occur, for example polyfills aren't provided by the library anymore, but it is now required to provide them yourself.
`PolyFillNotAvailable: Library cannot function without fetch. So, please provide polyfill for it.`

**Comment by mlichtblau** [comment]
In the meantime I think it would be helpful to link to the migration guide in the README.

**Comment by jasonjoh** [comment]
Thanks @mlichtblau. This is on the backlog.

**Comment by jasonjoh** [comment]
As it turns out all you really had to do to migrate this sample was:

- Update the Graph SDK
- `npm install isomorphic-fetch`
- Add `require('isomorphic-fetch');` to the top of graph.js

I've got these changes in my refresh, so this should be pushed to master today.
