### ISSUE TITLE
Time to complete?

### ISSUE THREAD

**Issue by pacific202** [microsoftgraph/msgraph-training-nodeexpressapp#33]
**Developer (Beginner)
31 minutes to complete**

The video is 51:37 :)

**Comment by jasonjoh** [comment]
That's true, but there's a lot of asides and explanations going on in the video. Have you attempted to go through it? If you do I'd love to hear how long it takes you.

**Comment by pacific202** [comment]
At the very least the time to complete should be adjusted to 52 minutes.

There was a lot (15m) of material at the start I wanted to skip through, I just wanted to get straight to building my app.  I need to copy a file into OneDrive using node, and I'm looking for something a lot more straightforward and direct.

**Comment by jasonjoh** [comment]
You're referring to the video? The time to complete is referring to a user going through the tutorial themselves, starting at https://docs.microsoft.com/en-us/graph/tutorials/node?tutorial-step=1, which does dive right in. If I'm misunderstanding your feedback, please let me know.

**Comment by pacific202** [comment]
Oh, I linked into this repository from another page that only had a link to the video itself and nothing more.

https://docs.microsoft.com/en-us/graph/tutorials/node

I now see a "Begin" button at the bottom, but I guess I'm conditioned to think that the page content has completed when I see a "Feedback" link/button and didn't notice it before.

**Comment by jasonjoh** [comment]
Ok, that's helpful to understand. The video was added to the intro afterward - we may need to rethink that if it's pushing the Begin button too far down.

**Comment by pacific202** [comment]
Unfortunately the tutorial doesn't seem to apply to me as it's so heavily node/express biased.  I'm trying to write a file to OneDrive from an Azure Function and need something a lot simpler to understand auth without passport.
