### ISSUE TITLE
"Error: failed to deserialize user out of session"

### ISSUE THREAD

**Issue by BrendyRyan** [microsoftgraph/msgraph-training-nodeexpressapp#35]
I get this error when I make a change to any of my files on the Express server. I have to close the browser and re-log in to get it working again (after nodemon restarts)

![image](https://user-images.githubusercontent.com/39662098/86192821-6ec16a00-bb18-11ea-9fad-8beb072d75a9.png)

I've tried the '**findByOid**' function from the passport-azure-ad walkthough 
(https://github.com/AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs/blob/master/app.js) 
but can't seem to get it working here.  It creates a loop and continuously tries to deserialize over and over.
Any help would be appreciated!

**From this example:**
```javascript
passport.deserializeUser(function(id, done) {
  done(null, users[id]);
});
```

**From passport-azure-ad example:**
```javascript
passport.deserializeUser(function(id, done) {
     findByOid(id, function(err, user) {
    done(err, user);
    });
});
```
```javascript
const users = [];

const findByOid = function(oid, fn) {
  for (let i = 0, len = users.length; i < len; i++) {
    const user = users[i];
    if (user.oid === oid) {
      return fn(null, user);
    }
  }
  return fn(null, null);
};
```

**Comment by jasonjoh** [comment]
This example uses a very basic in-memory construct to store users. It's likely that when you edit the files while the server is running, and nodemon does it's thing to recompile, it's invalidating that in-memory stuff. The browser still has it's cookies so it thinks it's logged in.

I don't know for sure, but probably what you should do as a minimal fix is check if `users[id]` is null or undefined, and if so, return an error. A "real" fix would be to use some sort of persistent storage for the user map, like a database.

**Comment by BrendyRyan** [comment]
Yes you are right, thank you. 

At least as a temporary fix until I can wrap my head around it further I did:

```javascript
passport.deserializeUser(function(id, done) {
  if (users[id] === undefined) {
    done(null, false);
  }
  done(null, users[id]);
});
```

Thanks again.
