### ISSUE TITLE
Is there an issue with using cookies instead of session?

### ISSUE THREAD

**Issue by MrJohnLocke** [microsoftgraph/msgraph-training-nodeexpressapp#36]
passport-azure-ad allows the use of cookies instead of session, but I'm finding with this graph tutorial that the callback response always seems to give the error "In collectInfoFromReq: invalid state received in the request".  The "passport-aad" cookie always has a value of 0.  What am I doing wrong?

In app.js: 
Additional options in OIDCStrategy:
nonceLifetime: 3600,
nonceMaxAmount: 10,
useCookieInsteadOfSession: true,
cookieEncryptionKeys: [ { key: '12345678901234567890123456789012', 'iv': '123456789012' }]

setting up cookies:
var cookieSession = require('cookie-session');
app.use(cookieParser());
app.use(cookieSession({
  name: 'session',
  secret: process.env.COOKIE_SECRET,
  maxAge: 24 * 60 * 60 * 1000
}));

Added `session: false` to passport.authenticate('azuread-openidconnect') for both /signin and /callback routes.

I'm using section 4.1.4 of https://github.com/AzureAD/passport-azure-ad as a reference for all of this.  I am just not having any luck.

**Comment by jasonjoh** [comment]
I honestly don't know, I've never used the `useCookieInsteadOfSession`. Have you opened an issue on the passport-azure-ad repo? You'll likely get better qualified assistance there.

**Comment by MrJohnLocke** [comment]
I will go do that now, thanks.
