### ISSUE TITLE
redirectUrl issue

### ISSUE THREAD

**Issue by peterfeng-hub** [microsoftgraph/msgraph-training-nodeexpressapp#42]
Can you please advise on how to address this issue I'm encountering?
`TypeError: Invalid value for redirectUrl.The URL must be valid and be https:// or http://`

The Redirect URI I configured in the .env file is `http://localhost:3000/auth/callback`.

**Comment by jasonjoh** [comment]
Can you provide more context? What line of code? When do you see this error, on compile or at runtime? Did you register `http://localhost:3000/auth/callback` as a redirect in the Azure portal?
