### ISSUE TITLE
Replace APP_PASSWORD with CLIENT_SECRET

### ISSUE THREAD

**Issue by glennblock** [microsoftgraph/msgraph-training-nodeexpressapp#44]
In the "Add Azure AD authentication" page, the document has the following instructions:

Replace `YOUR APP ID HERE` with the application ID from the Application Registration Portal, and replace `YOUR APP SECRET HERE` with the password you generated.

This is confusing and not up to date with the current portal experience. In the portal, it shows as "Client Secret"

![image](https://user-images.githubusercontent.com/141124/88705225-13a57780-d0c4-11ea-8492-370248f6dc92.png)

The environment variable should be renamed to CLIENT_SECRET and the description "YOU CLIENT SECRET HERE". This will require several changes in the code snippets.

**Comment by enak** [comment]
https://github.com/microsoftgraph/msgraph-training-nodeexpressapp/pull/43
