### ISSUE TITLE
getEvents snippet will not compile

### ISSUE THREAD

**Issue by glennblock** [microsoftgraph/msgraph-training-nodeexpressapp#45]
In "Get calendar data" copying the getEvents snippet into `calendar.js` will not compile as there is a missing comma. Depending on where the snippet is copied, the comma will need to be before or after. I recommend that we instruct the reader to copy getEvents as the first function in module.exports and add a comma to the snippet.

i.e.

```javascript
module.exports = {
  getEvents: async function(accessToken) {
    const client = getAuthenticatedClient(accessToken);

    const events = await client
    .api('/me/events')
    .select('subject,organizer,start,end')
    .orderby('createdDateTime DESC')
    .get();

    return events;
  },

  ...
```

**Comment by jasonjoh** [comment]
Fixed by #52
