### ISSUE TITLE
Mention OAuth related to refresh token to educate the reader

### ISSUE THREAD

**Issue by glennblock** [microsoftgraph/msgraph-training-nodeexpressapp#46]
In "Add Azure AD authentication"

"However, this token is short-lived. The token expires an hour after it is issued. This is where the refresh token becomes useful. The refresh token allows the app to request a new access token without requiring the user to sign in again."

Suggest we add a mention of OAuth for those who may not be familiar with refresh token

"However, this token is short-lived. The token expires an hour after it is issued. The OAuth specification introduces a refresh token to help here. The refresh token allows the app to request a new access token without requiring the user to sign in again"

**Comment by sobhardwaj** [comment]
what is the significance of refresh_token expire time 90 days, even every hour have to make a new request to get access_token ? is code available?

**Comment by jasonjoh** [comment]
This is all part of the OAuth spec, and you can read a lot more authoritative sources on this than what I can provide. However I'll give my two cents:

- The access token grants access to the resource, and is short-lived. This is to take care of situations where the user revokes access, or if somehow the token is leaked to a bad actor - the access will not be forever.
- The refresh token doesn't give you access to anything, but can be used by the app to get a fresh access token. The refresh token by itself cannot be used - you also need the app's ID and secret.

The code in this sample does all of this for you using the simple-oauth2 library. I'm in process of removing that library and using the msal-node package instead, which again, does all of this token management for you.

**Comment by jasonjoh** [comment]
Fixed by #52
