### ISSUE TITLE
Update simple-oauth2 to 4.1.0

### ISSUE THREAD

**Issue by absurdist81** [microsoftgraph/msgraph-training-nodeexpressapp#47]
Versions of simple-oauth2 above 3.4.0 do not have the require('simple-oauth2').create() function.

**Comment by jasonjoh** [comment]
I typically refresh these every 3-4 months to use the latest versions of dependencies.

**Comment by jasonjoh** [comment]
Resolved by #52. This tutorial no longer uses simple-oauth2. It has been replaced by [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node).
