### ISSUE TITLE
ReferenceError: state not defined

### ISSUE THREAD

**Issue by cbeech1980** [microsoftgraph/msgraph-training-nodeexpressapp#49]
I've cloned the repo and tried to run the example, but am hitting the following error...

```
state is not defined
ReferenceError: state is not defined
    at Strategy.collectInfoFromReq (/Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/passport-azure-ad/lib/oidcstrategy.js:709:78)
    at async.waterfall (/Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/passport-azure-ad/lib/oidcstrategy.js:616:21)
    at fn (/Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/async/lib/async.js:746:34)
    at /Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/async/lib/async.js:1213:16
    at /Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/async/lib/async.js:166:37
    at /Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/async/lib/async.js:706:43
    at /Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/async/lib/async.js:710:44)
    at Strategy.authenticateStrategy [as authenticate] (/Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/passport-azure-ad/lib/oidcstrategy.js:610:9)
    at attempt (/Users/chrisbeech/work/msgraph-training-nodeexpressapp/demo/graph-tutorial/node_modules/passport/lib/middleware/authenticate.js:348:16)
```

It's an error 500 being thrown from /auth/callback. All I've changed is the .env file to set my app ID and secret.

What am i doing wrong?

**Comment by jasonjoh** [comment]
Sorry you're seeing this. What version of Node are you using?

**Comment by cbeech1980** [comment]
I’m using 10.16.3.

**Comment by jasonjoh** [comment]
The error seems to indicate that there was no `state` parameter in the auth response back from Microsoft identity platform. This could be due to an app registration issue. I'm trying to reproduce it, but in the meantime, could you add `console.log(JSON.stringify(req.body));` in the callback in auth.js, right before the call to `passport.authenticate`?

```
router.post('/callback',
  function(req, res, next) {
    console.log(JSON.stringify(req.body));
    passport.authenticate('azuread-openidconnect',
      {
        response: res,
        failureRedirect: '/',
        failureFlash: true,
        successRedirect: '/'
      }
    )(req,res,next);
  }
);
```

Try to login again, then see what is output to the console. There may be an error back from the login that could shed some light.

**Comment by jasonjoh** [comment]
I have not been able to reproduce this error. A few other things to check.

- When you registered the app, did you select **Accounts in any organizational directory and personal Microsoft accounts** for supported account types?
- Did you enable ID tokens in the Implicit grant section of the app registration?
- Did you get prompted with the list of permissions before this error, or did the error come right after authenticating?
- Are you authenticating with a M365 account (work/school) or a personal Microsoft account (outlook.com)?

**Comment by cbeech1980** [comment]
I was using Azure Gov, as soon as I moved over to Azure Commercial it worked as expected – not sure why there’s a difference there, but this isn’t the first time I’ve experienced inconsistencies between functionality running on Gov vs Commercial.

As an aside, what difference would configuring this to work for users only in the current tenant make to the implementation? The reason I ask that is because of your first clarification point below, which makes me think the implementation details could be different depending on directory scope.
