### ISSUE TITLE
Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute

### ISSUE THREAD

**Issue by manwey** [microsoftgraph/msgraph-training-nodeexpressapp#51]
After sign in, in http://localhost:3000/ there are two warnings in the browser with the same issue:

Indicate whether to send a cookie in a cross-site request by specifying its SameSite attribute
Because a cookie's SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which will prevent the cookie from being sent in a cross-site request in a future version of the browser. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests

- AFFECTED RESOURCES

1 Cookie
                     Name | Domain & Path
                     -- | --
                     connect.sid | localhost/

1 Request
                     localhost
 
- AFFECTED RESOURCES

1 Cookie
                     Name | Domain & Path
                     -- | --
                     _ga	localhost/

1 Request
                     localhost

**Comment by jasonjoh** [comment]
@manwey I cannot reproduce this with the latest code. I've recently refreshed this tutorial, so it may be something that was resolved by updates. Can you try with the latest code?

If you do still reproduce it, can you provide details on which browser you're using?

**Comment by manwey** [comment]
Hi @jasonjoh,

Thank you for your answer,  for the tutorial and the latest code.

I tried the latest code and I think it is working right now. 

Should not the project install the package dotenv as a devDependency? (As we don't need this in production)

npm i -D dotenv

**Comment by jasonjoh** [comment]
As it's currently written it isn't a dev dependency. This line in app.js would fail:

```
require('dotenv').config();
```

**Comment by manwey** [comment]
You are right, and this line will fail.

Thank you for your answers, I learned a lot from you.
