### ISSUE TITLE
Error: Cannot find module 'express-promise-router'  in step 04-add-aad-auth.md of tutorial

### ISSUE THREAD

**Issue by letzfets** [microsoftgraph/msgraph-training-nodeexpressapp#57]
### Where did you get the code?

- [ ] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [X] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

### Describe the bug

When starting the web server, just before the section **Get user details**, the nom start fails with _Error: Cannot find module 'express-promise-router'_

### To Reproduce

1. Follow the tutorial until step 4
1. Start the webserver with ´npm start`

### Expected behavior

The webserver starts

### Additional context

running `npm install express-promise-router` fixes the issue 

Btw: you have copied the `<MsalInitSnippet>` in the demo AFTER `var app = express();`, whereas the tutorial says before `var indexRouter = require('./routes/index');` - which gives another error. Demo file here in GitHub seems fine (and more logical)

**Comment by jasonjoh** [comment]
Thanks for reporting. I'll get this fixed.
