### ISSUE TITLE
TypeError: Cannot read property 'locals' of undefined

### ISSUE THREAD

**Issue by FilaCZ** [microsoftgraph/msgraph-training-nodeexpressapp#58]
Hi there,

I am currently on **Add Azure AD authentication** step of the tutorial and finished right before Get user details. Only thing I needed right now was to type npm start and see the result on the localhost. When I hit npm start in shell I get this error related to locals property. I went step by step and tried it twice with the same result. Am I missing anything? 

I am also beginner so I might overlook something or I just don't see something what could be obvious to others. 

Thank you in advance.

Filip

![error](https://user-images.githubusercontent.com/41991774/103475579-95ee4200-4dae-11eb-801d-2139e395ec52.png)

**Comment by jasonjoh** [comment]
It sounds like it may be an issue with where that line appears in your app.js. Make sure that it is *after* the `var app = express();` line.

**Comment by jasonjoh** [comment]
As mentioned in #57, the instructions on where to put that code were wrong and likely are causing your problem. Let me know if moving the code does not fix your problem.
