### ISSUE TITLE
How to maintain the AccessToken with load balancer

### ISSUE THREAD

**Issue by ubukawa** [microsoftgraph/msgraph-training-nodeexpressapp#62]
Hello. I have added new pages to your sample tutorial.  
But I have a problem. Could you kindly advise me?  

# Situation
New pages worked well including the authentication function with single web server (single process).  
However, once I run the server using a load balancer, specifically the cluster mode of PM2, the sign in process is required again when I move to pages. (After I sign in again, I can move to another page, but it happens again.)  
I noted that there is no error with PM2 if I did not use cluster mode.   
So, I think the issue is that how I can maintain accesstoken when I run a server using load balancer.  

# Question
Do you have a similar experience? and, is it possible to keep access token among the webpage when the server runs with load balancer?

# Additional information  
--I added the following lines in app.js---  
var newpageRouter = require('./routes/newpage')
app.use('/newpage', newpageRouter)

-- I made "newpage.hbs"  

---I created routes/newpage.js as below---  
var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', 
 async function(req, res, next) {

if (!req.session.userId) {
  // Redirect unauthenticated requests to home page
    res.redirect('/')
    } else {
  let params = {
    active: { home: true }
     };

// Get the user
   const user = req.app.locals.users[req.session.userId];

// Get the access token
   var accessToken;
    try {
      accessToken = await getAccessToken(req.session.userId, req.app.locals.msalClient);
    } catch (err) {
      res.send(JSON.stringify(err, Object.getOwnPropertyNames(err)));
      return;
    }

 if (accessToken && accessToken.length > 0) {
      try {
        // render
          res.render('newpage',{ layout: false } ); 
          //   res.render('newpage', params); 
       } catch (err) {
        res.send(JSON.stringify(err, Object.getOwnPropertyNames(err)));
       }
     }
     else {
       req.flash('error_msg', 'Could not get an access token');
     }
    }
  }
);

async function getAccessToken(userId, msalClient) {
  // Look up the user's account in the cache
  try {
    const accounts = await msalClient
      .getTokenCache()
      .getAllAccounts();

 const userAccount = accounts.find(a => a.homeAccountId === userId);

    // Get the token silently
    const response = await msalClient.acquireTokenSilent({
      scopes: process.env.OAUTH_SCOPES.split(','),
      redirectUri: process.env.OAUTH_REDIRECT_URI,
      account: userAccount
    });

    return response.accessToken;
  } catch (err) {
    console.log(JSON.stringify(err, Object.getOwnPropertyNames(err)));
  }
}

module.exports = router;

**Comment by jasonjoh** [comment]
That's a bit beyond the scope of this sample. I would assume that this is caused because the MSAL caches are in-memory, and server2 can't see the the caches on server1. You can implement your own caching method to do something like store them in a database that both servers can access, etc.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/configuration.md

**Comment by ubukawa** [comment]
Thank you very much for your help! 
I will learn from your URL. Thank you very much!!
