### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by piotrlech** [microsoftgraph/msgraph-training-nodeexpressapp#63]
For some reason the getAuthCodeUrl does not use proxy, but calls the https://graph.windows.net/ directly. How do I setup my proxy for that case? On the other hand the browser works correctly - the https://graph.windows.net/ goes via proxy

**Comment by jasonjoh** [comment]
Probably a question for the MSAL folks as `getAuthCodeUrl` is implemented inside the `@azure/msal-node` package. You can find their repository here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node
