### ISSUE TITLE
Why is isomorphic-fetch required?

### ISSUE THREAD

**Issue by diberry** [microsoftgraph/msgraph-training-nodeexpressapp#67]
Why is isomorphic-fetch required if the npm package for ms graph is used? Can't the npm package include that fetch package?

**Comment by jasonjoh** [comment]
That's probably a better question for the [SDK repo](https://github.com/microsoftgraph/msgraph-sdk-javascript/). However, my guess is that they wanted to make it opt-in, since `fetch` is supported in browsers, it only needs to be polyfilled in Node.js apps.

**Comment by jasonjoh** [comment]
Ah yes, already asked/answered over there: https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/405#issuecomment-805288347
