### ISSUE TITLE
Calendar View Not Pulling Calendar Events

### ISSUE THREAD

**Issue by winstonthart** [microsoftgraph/msgraph-training-nodeexpressapp#73]
- Default app running local host on windows surface pro x using Visual Studio Code.
 - Signs in correctly and allows me to create an event
 - Calendar events do not come through at all. Every time the calendar page is refreshed, there are no events, even though there should be

**Comment by jasonjoh** [comment]
Just to be clear: it will only show events for the current week. If you have events on your calendar for the current week, you'll need to dig into the problem a bit more, there's not enough information to hazard a guess.

Adding some logging inside `router.get` in calendar.js might help track this down. Verify what time zone, week start, and week end values are.

**Comment by winstonthart** [comment]
Thanks for your comment, I figured out that it worked when putting in manual _string_ start and end times in graph.js - or in router.get('/', in calendar.js in place of the formatISO(weekStart) and formatISO(weekEnd). However, these values appear to need strings for it to be recognised by the graph api? It is getting transferred as a date format and it doesn't seem to be working. The results of formatISO when logging appear to be correct, but they are logged as dates and not as strings it seems

**Comment by winstonthart** [comment]
Ok, fixed by using weekStart.toISOString().slice(0,-5)+"Z" in place of formatISO(weekStart) and same for weekEnd in calendar.js
Is this the correct approach?

**Comment by jasonjoh** [comment]
Hmm interesting. The `formatISO` function comes from `date-fns`. What version do you have installed? I'll try updating on my end and see if it reproduces the problem.

**Comment by jasonjoh** [comment]
I currently have 2.23.0 for `date-fns`, and I get this in the console when rendering a calendar view successfully.

```
Start: 2021-12-05T03:00:00-05:00
```

I then updated to latest `date-fns` (2.27.0) and re-tested. I got the exact same output, so probably the `date-fns` version doesn't matter.

What does `formatISO(weekStart)` return for you? I don't think your solution using `slice` is correct because you're dropping the offset, so you're likely not getting the right start and end times (unless you happen to be in UTC+0 timezone).

**Comment by winstonthart** [comment]
I updated from 2.22 to 22.23.0 but still having the same issue. formatISO(weekStart) returns 2021-12-05T00:00:00+08:00. However, graph.js only works if it is turned into this: 2021-12-04T16:00:00Z (which is returned from weekStart.toISOString().slice(0,-5)+"Z". Could it be a timezone issue? Timezone is Australian Western Standard Time

**Comment by jasonjoh** [comment]
That format *should* be valid. I think what's happening is the `+` sign is messing with the URL. `+` denotes an encoded space in a URL. It may be necessary to URL-encode the value (though I thought the Graph SDK handled this).

I tested it, and confirmed. The proper fix here is to update `getCalendarView` in graph.js:

```typescript
getCalendarView: async function(msalClient, userId, start, end, timeZone) {
  const client = getAuthenticatedClient(msalClient, userId);

  return client
    .api('/me/calendarview')
    // Add Prefer header to get back times in user's timezone
    .header("Prefer", `outlook.timezone="${timeZone}"`)
    // Add the begin and end of the calendar window
    .query({
      startDateTime: encodeUriComponent(start),
      endDateTime: encodeURIComponent(end)
    })
    // Get just the properties used by the app
    .select('subject,organizer,start,end')
    // Order by start time
    .orderby('start/dateTime')
    // Get at most 50 results
    .top(50)
    .get();
},
```

Notice the change to the values passed to `.query` - they now are wrapped by `encodeURIComponent`.

**Comment by winstonthart** [comment]
Unfortunately that fix does not seem to work for me, and I'm not sure why. I copied it exactly to replace the getCalendarView function. Could it be some issue with the operating system? Running Windows 11 Insider Preview on ARM based surface pro X in an Australian Time Zone

**Comment by jasonjoh** [comment]
Maybe it's because of my typo in the first instance. Proper function name is `encodeURIComponent` (`URI` should be all caps).

**Comment by winstonthart** [comment]
Excellent, worked perfectly! Thank you!
